action_noise:
  mean: 0
  sigma: 0.25
device: cpu
env:
  discrete_action_space: true
  discrete_action_step: 0.1
  discrete_observation_space: true
  discrete_observation_step: 0.1
  entry_point: simglucose.envs:T1DSimGymnaisumEnv
  id: simglucose/multi-patient-v0
  max_episode_steps: 480
  patient_name: all
eval:
  eval_freq: 5000
  n_eval_episodes: 5
mode:
- train
- predict
model:
  batch_size: 128
  buffer_size: 100000
  gamma: 0.999
  learning_rate: 1.0e-05
  policy: MlpPolicy
model_name: DQN
model_save_path: checkpoints/final_model
predict:
  prefix: adolescent#002
run_directory: /u201/y329xie/rl-insulin-pump/runs/dqn-run-with-paper-params
seed: 42
training:
  checkpoint_freq: 10000
  total_timesteps: 4800000
