env:
  id: "simglucose/multi-patient-v0"
  entry_point: "simglucose.envs:T1DSimGymnaisumEnv"
  max_episode_steps: 1000
  patient_name: "all"  # Use all available patients, can also be a list of patient names or a single patient name
  discrete_action_space: True
  discrete_observation_space: True
  discrete_action_step: 0.1
  discrete_observation_step: 0.1
seed: 42
model_name: "DQN"
action_noise:
  mean: 0
  sigma: 0.25
model:
  policy: "MlpPolicy"
  learning_rate: 0.001
  buffer_size: 100000
  batch_size: 256
  gamma: 0.99
training:
  total_timesteps: 1000
  checkpoint_freq: 10000
eval:
  eval_freq: 5000
  n_eval_episodes: 5
predict:
  prefix: "adolescent#002"
device: "cpu"
mode: ["train", "predict"]
model_save_path: "checkpoints/final_model"