env:
  id: "simglucose/multi-patient-v0"
  entry_point: "simglucose.envs:T1DSimGymnaisumEnv"
  max_episode_steps: 10000
  patient_name: "all" # Use all available patients, can also be a list of patient names or a single patient name
  discrete_action_space: False
  discrete_observation_space: False
seed: 42
model_name: "BB"
action_noise:
  mean: 0
  sigma: 0.25
model:
  kwargs:
    target: 140
eval:
  eval_freq: 5000
  n_eval_episodes: 5
predict:
  predict_steps: 1000
device: "cpu"
run_directory: "./runs/local_bb"
mode: ["predict", "analyze"]
