env:
  id: "simglucose/multi-patient-v0"
  entry_point: "simglucose.envs:T1DSimGymnaisumEnv"
  max_episode_steps: 10000
  patient_name: "all" # Use all available patients, can also be a list of patient names or a single patient name
seed: 42
run_directory: "RUN_DIR"
model_name: "DDPG"
action_noise:
  mean: 0
  sigma: 0.25
model:
  learning_rate: 0.001
  buffer_size: 100000
  batch_size: 256
  gamma: 0.99
  policy: "MlpPolicy"
training:
  total_timesteps: 10000
  checkpoint_freq: 1000
eval:
  eval_freq: 5000
  n_eval_episodes: 5
predict:
  prefix: "adolescent#002"
  predict_steps: 20
device: "cpu"
mode: ["train", "predict"]
