name: Pre-commit checks
on:
  pull_request:
    branches: [ main ]

jobs:
  precommit:
    name: Lint, format, and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        # Install simglucose in editable mode with legacy mode for compatibility
        pip install -e ./simglucose --config-settings editable_mode=compat

    - name: Run pre-commit
      run: |
        pip install pre-commit
        pre-commit run --all-files

    - name: Run tests
      run: |
        # Only run tests from the main tests directory, explicitly exclude simglucose tests
        pytest tests/ -v --color=yes --ignore=simglucose/
